import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { GitProviderError } from './git-provider.ts';
import { GitHubGitProvider, type GitHubGitClient } from './github-git-provider.ts';
import { MockGitProvider } from './mock-git-provider.ts';
import type { GitRepositoryRef } from './types.ts';

const repository: GitRepositoryRef = { owner: 'acme', name: 'platform-web' };

function createProvider(): MockGitProvider {
  return new MockGitProvider([
    {
      ref: repository,
      defaultBranch: 'main',
      branches: [{ name: 'main', commitSha: 'sha-main', protected: true }],
      commits: [
        {
          sha: 'sha-main',
          message: 'Initial commit',
          authorName: 'Forge',
          authoredAt: new Date('2026-09-24T00:00:00.000Z'),
          parentShas: [],
        },
      ],
      checks: {
        'sha-main': [{ name: 'unit', status: 'completed', conclusion: 'success', detailsUrl: null }],
      },
    },
  ]);
}

describe('MockGitProvider', () => {
  it('lista branch default e checks determinísticos', async () => {
    const provider = createProvider();

    assert.deepEqual(await provider.getDefaultBranch(repository), {
      name: 'main',
      commitSha: 'sha-main',
      protected: true,
    });
    assert.equal((await provider.listChecks(repository, 'sha-main')).length, 1);
  });

  it('cria branch, commit, diff e pull request em memória', async () => {
    const provider = createProvider();

    const branch = await provider.createBranch({ repository, name: 'feat/fix-currency', fromSha: 'sha-main' });
    assert.equal(branch.protected, false);

    const commit = await provider.createCommit({
      repository,
      branchName: 'feat/fix-currency',
      message: 'fix: preserve negative currency values',
      authorName: 'Forge AI',
      files: [{ path: 'src/lib/format-currency.ts', content: 'export const fixed = true;' }],
    });
    assert.deepEqual(commit.parentShas, ['sha-main']);

    const diff = await provider.getDiff(repository, 'sha-main', commit.sha);
    assert.equal(diff.files[0]?.path, 'src/lib/format-currency.ts');

    const pullRequest = await provider.createPullRequest({
      repository,
      title: 'Fix currency formatting',
      body: 'Generated by Forge.',
      headBranch: 'feat/fix-currency',
      baseBranch: 'main',
    });
    assert.match(pullRequest.url, /\/acme\/platform-web\/pull\/1/);
  });

  it('falha de forma explícita ao referenciar branch inexistente', async () => {
    const provider = createProvider();

    await assert.rejects(
      async () =>
        await provider.createCommit({
          repository,
          branchName: 'missing',
          message: 'noop',
          authorName: 'Forge AI',
          files: [],
        }),
      GitProviderError,
    );
  });
});

describe('GitHubGitProvider', () => {
  it('delega operações para uma fronteira de cliente injetada', async () => {
    const client: GitHubGitClient = {
      getDefaultBranch: async () => ({ name: 'main', commitSha: 'sha-main', protected: true }),
      listBranches: async () => [],
      getCommit: async () => ({
        sha: 'sha-main',
        message: 'Initial commit',
        authorName: 'Forge',
        authoredAt: new Date('2026-09-24T00:00:00.000Z'),
        parentShas: [],
      }),
      getDiff: async (_repository, baseSha, headSha) => ({ baseSha, headSha, files: [] }),
      createBranch: async (input) => ({ name: input.name, commitSha: input.fromSha, protected: false }),
      createCommit: async () => ({
        sha: 'sha-new',
        message: 'commit',
        authorName: 'Forge',
        authoredAt: new Date('2026-09-24T00:00:00.000Z'),
        parentShas: ['sha-main'],
      }),
      createPullRequest: async (input) => ({
        id: '1',
        number: 1,
        title: input.title,
        url: 'https://github.example/pull/1',
        headBranch: input.headBranch,
        baseBranch: input.baseBranch,
        status: 'open',
      }),
      listChecks: async () => [],
    };

    const provider = new GitHubGitProvider(client);

    assert.equal((await provider.getDefaultBranch(repository)).name, 'main');
  });
});
